<?php 

return  [
        'contact' => [
            'phone' => '059.113.114',
            'signup_advice' => 'ĐĂNG KÝ TƯ VẤN',
            'ask' => 'HỎI ĐÁP',
            'abc' => 'Nhap ngu'
        ],
        'stage' => [
            'pending' => 'Đang chờ',
            'inprogress' => 'Trong quá trình',
            'done' => 'Xong'
        ],
        'shapes' => [
            'poly' => 'Đa giác',
            'rect' => 'vuông',
            'circle' => 'Tròn'
        ],
        'priceRange' => [
            'min' => 200,
            'max' => 1000000000
        ],
        'priceDropdown' => [
            '200-1.000 円' => '200;1000',
            '1.001-5.000 円' => '1001;5000',
            '5.001-1.0000 円' => '5001;10000',
            '10.001-20.000 円' => '10001;20000',
            '20.001-50.000 円' => '20001;50000',
            '50.001-100.000 円' => '50001;100000',
        ],
        'acreageRange'=> [
            'min' => 0,
            'max' => 50000
        ],
        'acreageDropdown' => [
            '0-100' => '0;100',
            '101-200' => '101;200',
            '201-300' => '301;400',
            '301-400' => '301;400',
            '401-500' => '401;500'
        ],
        'defautuser' => "(1, 'Mr. Admin', 'admin@admin.com', NULL, $2y$10\$RtVmSU6Bot9emNoca.eUxuMUDVf4PwOEgxJnDeywo0aMATFn5gA.u', 1, 'default.png', 1, 'v1WweocPEYlY95n0vyWrI5csuBA8lTg4lq9LcPoEx27G6YZGBv5bYqKq8qwg', '2020-07-18 05:27:53', '2020-07-24 18:22:40')",
        'text' => [
            'staff' => "スタッフ",// nhân viên
            'views' => 'ビュー',
            'comments' => 'コメント',
            'leave_a_reply' => '返信を残す',
            'enter_your_name_here' => 'ここにあなたの名前を入力してください',
            'enter_your_email_here' => 'あなたのメールアドレスをここに入力してください',
            'enter_your_website_here' => 'ここにあなたのウェブサイトを入力してください',
            'enter_your_comment_here' => 'ここにコメントを入力してください',
            'post_comment' => 'コメントを投稿',
            'leave_cmt_success' => 'コメントを残してください！',
            'info_submit_success'=> '情報送信の成功',
            'monday_to_friday' => '月曜日から土曜日まで',
            'send_us_your_query_anytime' => 'いつでもお問い合わせください！',
            'category' => 'カテゴリー',
            'district' => '地区',
            'status' => '状態',
            'type' => 'タイプ',
            'price'     =>'価格',
            'acreage'=>'エーカー',
            'floors' => '床',       // tầng
            'rooms' => '部屋',
            'bathrooms' => 'バスルーム',
            'bedrooms' => 'ベッドルーム',
            'host_name' => 'ホスト名',
            'yen' => '円',
            'address' => '住所',
            'contract_now' => '今すぐ契約',
            'tags_cloud' => 'タグクラウド',
            'post_categories'=> '投稿カテゴリ',
            'properties_in_various_cities'=>'さまざまな都市のプロパティ',
            'extremely_love'=>'環境にやさしいシステムを非常に愛している人。',
            'make_an_appointment'=>'予約する',
            'name' => '名前',
            'enter_your_name' => 'あなたの名前を入力してください',
            'email' => 'Eメール',
            'enter_your_email'=>'メールアドレスを入力',
            'request_asset' => 'アセットをリクエストする',
            'enter_subject'=> '件名を入力してください',
            'subject'=> '件名',
            'phone_number'=>'電話番号',
            'enter_your_phone_number'=>'電話番号を入力してください',
            'appointment'=>'予定',
            'enter_appointment_date'=> '予約日を入力してください',
            'message'=>'メッセージ',
            'enter_message'=> 'メッセージを入力してください',
            'send_message'=> 'メッセージを送る',
            'vacancy_room_rent_rental'=>'空　室　賃　貸　物　件',
            'new_arrival_vacant_room_rent_rental'=> '新 着 空 室 賃 貸 物 件',
            'someone_who_loves_the_environment_friendly_system_very_much'=>'環境にやさしいシステムを非常に気に入っている人。',
            'about_us'=> '会社概要',
            'property'=>'業務内容',
            'agents'=>'従業員紹介',
            'contract_flow'=>'契約の流れ',
            'contact'=>'お問い合せ',
            'slogan'=> 'お客様の利益と満足を第一に考え、価値ある資産づくりと良質な物件のご提供をお手伝いいたします。',
            'new_vacant_rental_property'=>'新 着 空 室 賃 貸 物 件',
            'room_count'=>'部屋数',
            'floor_count'=>'フロア数',
            '1_room'=>'一つの部屋があります',
            '2_room'=>'二つの部屋があります',
            '3_room'=>'三つの部屋があります',
            '1_floor'=> '一階あり',
            '2_floor'=> '二階あり',
            '3_floor'=> '三階あり',
            'price_range'=> '価格帯',
            'area_range'=>'エリア範囲 (平方メートル):',
            'search'=>'探す',
            'post_comment'=>'コメントを投稿',
            'asset_detail'=>'物件の詳細情報',
            'map'=>'地図',
            'created_at'=> '作成日',
            'description'=> '説明',
            'writer' => '作家',
            'is_foreign_nationality_consultation'=> "外国籍相談可",
            'is_newly_built_properties'=> "新築物件",
            'free_first_months'=>'フリーレント',
            'greater_than_x_month'=>'ヶ月以上',
            'bus_station_distance'=> '駅徒歩',
            'lower_than_x_meter'=>'メートルより低い',
            'receiving_time'=>'入居可能時期',
            'lower_than_x_weeks'=>'週間未満',
            'all'=> 'すべて'
        ]
];